Pass Requests adapters via ANYMAIL_REQUESTS_ADAPTERS configuration
anymail/django-anymail pull request #277
Opened 2022-06-03 18:09 UTC by dgilmanAIDENTIFIED

The requests library lets you mount adapters to configure policy such as timeouts and retries. Here's an attempt at an API that extends anymail to let you do so. This is the initial draft, I am looking forward to feedback on how this should be done. I also skipped writing docs.

2022-06-05 22:00 UTC, medmunds commented
@dgilmanAIDENTIFIED cool, thanks for this! You've integrated it nicely into Anymail.

My one concern is whether there are a bunch of other requests.Session options we'd want to expose in a similar way. E.g., `cert` for a custom client certificate, or `proxies`. (And if so, what happens in future requests releases?) I'd like to avoid Anymail having a lot of requests-specific settings.

A more general approach could be a "session creation hook", which Anymail would call with the new session. Clients could do anything they want to that session, including mounting transport adapters. I'd probably lean toward Django's signal receiver mechanism to implement the hook (Anymail already uses it for some [other hook-type features](https://anymail.dev/en/stable/sending/signals/)), but a setting could work, too.

Or one other way to modify the requests.Session—and this works in the current Anymail—is subclassing. You can subclass any Anymail requests-based backend to modify the session after it's created (or even create the session in a completely different way), and just set Django's EMAIL_BACKEND to your subclass. Right now, you have to override `AnymailRequestsBackend.open()`, which is a little ugly. It would probably be good to extract an `AnymailRequestsBackend.create_session()` method with base implementation `return requests.Session()`, just to facilitate this sort of override.

2022-06-06 12:19 UTC, dgilmanAIDENTIFIED commented
Those are all good ideas. If you can flip a coin or whatever and pick one I'll give it a shot. I think any of these are good ways forward as long as they're documented.

2022-06-08 13:04 UTC, dgilmanAIDENTIFIED commented
My big use case is automatic retries on network errors. I was planning on documenting it on the one doc page that mentions how to catch network errors and retries in a background task.

2022-06-14 16:20 UTC, medmunds requested changes
Nice! I didn't know about retryable adapters.

Couple of minor changes requested in review comments.

2022-06-14 16:20 UTC, medmunds commented on anymail/backends/base_requests.py
>          try:
The try … except fail_silently handling should remain in `open()`, so it will also apply to any subclass overrides. (But all of the session headers and hooks patching can stay here in `create_session()`.)

Also, I guess we should switch to a broad `except Exception:` with this change, since subclasses might generate non-RequestException errors that should still fail silently. (The fail-silently logic needs to suppress all potential runtime errors.)

2022-06-14 16:20 UTC, medmunds commented on anymail/backends/base_requests.py
> +    def create_session(self):
Please move `create_session()` down with the other overridable methods (after `_send()`), and add a doc comment that it must return a requests.Session and indicating subclasses can override to augment the session, but should generally call the super method to create it.

2022-06-27 01:35 UTC, medmunds approved these changes

2022-06-27 01:52 UTC, merged

2022-06-27 01:53 UTC, medmunds commented
Looks great. Thank you for the contribution!